// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgwV6PRd4eazTJVSjAmj-zvvs6Ac1ty_s',
    appId: '1:773372748774:web:8c8cf180c326d9af20ac27',
    messagingSenderId: '773372748774',
    projectId: 'edajcapp',
    authDomain: 'edajcapp.firebaseapp.com',
    storageBucket: 'edajcapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs6h4PQ_Xok6tRMEEQmYX53B7HsbFKUO4',
    appId: '1:773372748774:android:83388665926631f520ac27',
    messagingSenderId: '773372748774',
    projectId: 'edajcapp',
    storageBucket: 'edajcapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAffcOPZC2dQm7kGWRTGcYw5CBWAZqsRB4',
    appId: '1:773372748774:ios:efea784c2986c73d20ac27',
    messagingSenderId: '773372748774',
    projectId: 'edajcapp',
    storageBucket: 'edajcapp.firebasestorage.app',
    iosBundleId: 'top.flareline.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAffcOPZC2dQm7kGWRTGcYw5CBWAZqsRB4',
    appId: '1:773372748774:ios:efea784c2986c73d20ac27',
    messagingSenderId: '773372748774',
    projectId: 'edajcapp',
    storageBucket: 'edajcapp.firebasestorage.app',
    iosBundleId: 'top.flareline.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgwV6PRd4eazTJVSjAmj-zvvs6Ac1ty_s',
    appId: '1:773372748774:web:cc430d8ce687153420ac27',
    messagingSenderId: '773372748774',
    projectId: 'edajcapp',
    authDomain: 'edajcapp.firebaseapp.com',
    storageBucket: 'edajcapp.firebasestorage.app',
  );
}
